const express = require('express')
const router = express.Router()
const { handleUserSignup, handleUserLogin, handleVerify, handleLogout, handleUserDetalis, handleVerifyUsers, editUserProfile, findEmail, changePassword, allUsers, isAdmin, PromoteToAdmin, demoteToUser } = require('../Controllers/UserController.js')
const handleContact = require('../Controllers/ContactUsController.js')
const protection = require('../Middleware/check-auth.js')


router.post('/signup', handleUserSignup)
router.post('/login', handleUserLogin)
router.post('/contactus', handleContact)
router.get('/payment', handleVerify)
router.use(protection)
router.post('/logout', handleLogout)
router.get('/profile', handleVerifyUsers, handleUserDetalis)
router.put('/changeprofile', handleVerifyUsers, editUserProfile)
router.get('/getemail', handleVerifyUsers, findEmail)
router.put('/changepassword', handleVerifyUsers, changePassword)
router.get("/users", allUsers)
router.use(isAdmin)
router.put("/promote", PromoteToAdmin)
router.put("/demote", demoteToUser)
module.exports = router